---
- name: Deploy Web Server
  hosts: webserver
  become: true

  tasks:
    - name: Install apache_web_server
      apt:
        name: apache2
        state: present

    - name: start apache
      service:
        name: apache2
        state: started

    - name: enable apache_service_on_boot
      service:
        name: apache2
        enabled: yes
